#!/bin/sh
# build -- Build Script for the Intranet Application

TOMCAT_HOME=/opt/jakarta-tomcat
export TOMCAT_HOME

CLASSPATH=$CLASSPATH:/usr/jdk118/lib/classes.zip:$TOMCAT_HOME/classes:$TOMCAT_HOME/lib/ant.jar:$TOMCAT_HOME/lib/xml.jar:$TOMCAT_HOME/lib/jasper.jar:$TOMCAT_HOME/lib/servlet.jar:$TOMCAT_HOME/lib/webserver.jar
export CLASSPATH

/usr/jre118/bin/jre -classpath $CLASSPATH -Dtomcat.home=$TOMCAT_HOME org.apache.tools.ant.Main "$@"
