package org.haywired.firefly.wiki;
/* Generated By:JavaCC: Do not edit this line. TranslatorConstants.java */
public interface TranslatorConstants {

  int EOF = 0;
  int PAGE = 7;
  int LINK = 8;
  int BOOK = 9;
  int EOL = 10;
  int OTHER = 11;
  int BLANK = 12;
  int SPACE = 13;
  int TAB = 14;
  int RULE = 15;
  int BULLET = 16;

  int DEFAULT = 0;
  int BEGIN = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"\\\'\\\'\"",
    "\"\\\'\\\'\\\'\"",
    "\"&\"",
    "\"<\"",
    "\">\"",
    "\"\\\"\"",
    "<PAGE>",
    "<LINK>",
    "<BOOK>",
    "<EOL>",
    "<OTHER>",
    "<BLANK>",
    "\" \"",
    "\"\\t\"",
    "<RULE>",
    "\"*\"",
    "\"\"",
  };

}
